customhost = "employee.c0rjyw0pzejy.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chenkokfong-employee"
customregion = "us-east-1"
